######################################################################
# Automatically generated by qmake (1.07a) Mon Aug 20 11:06:58 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
