# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/qt3

HEADERS += form1.h \
           form1.ui.h 
SOURCES += qt3.cpp \
           form1.cpp 
TARGET=../bin/qt3
