######################################################################
# Automatically generated by qmake (2.01a) mer. 6. déc. 01:10:10 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
