# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/finddlg

HEADERS += finddialog.h 
SOURCES += finddlg.cpp \
           finddialog.cpp 
TARGET=../bin/finddlg
