######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 27 23:41:13 2010
######################################################################

TEMPLATE = app
TARGET = vlcdemo 
DEPENDPATH += .
INCLUDEPATH += .
# Input
LIBS += -L/usr/lib -lvlc
HEADERS += vlc_on_qt.h
SOURCES += main.cpp vlc_on_qt.cpp
